import { StyleSheet } from "react-native";
import { height, width} from '../../constants/constants'

const styles = StyleSheet.create({
    Container:{
        flex:1,
        backgroundColor:"white"
    },
    pricing:{
        flexDirection:"row",
        marginLeft:15,
        width:"50%",
        alignItems:"center",
        justifyContent:"space-between"
    },
    name:{
        fontSize:28,
        color:"black",
        fontWeight:"100",
        maxWidth:"60%",
        margin:15
    },
    price:{
        fontSize:22,
        fontWeight:"800",
        color:"black",
        
    },
    rating:{
        flexDirection:"row",
        marginLeft:10
    },
    ImageContainer:{
        width:"100%",
        height:"40%",
        backgroundColor:"white",
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
    },
    image:{
        width:"100%",
        height:"95%",
        resizeMode:"contain",
             
    },
    column:{
        width:"85%",
        height:"100%",
        flexDirection:"column",
        alignItems:"center",
        justifyContent:"space-between"
    },
    indicatorContainer:{
        width:"30%",
        height:"5%",
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-evenly",
        alignSelf:"center",
    },
    indicator:{
        height:10,
        width:10,
        borderRadius:100,
        backgroundColor:"black"
    },
    total:{
        marginLeft:10
    },
    secondHeading:{
        flexDirection:"row",
        width:"100%",
        alignItems:"center",
        justifyContent:"space-between",
        paddingHorizontal:20
    },
    icons:{
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between",
        width:"18%"
    },
    heading:{
        color:"black",
        fontSize:18,
        fontWeight:"700"
    },
    colorContainer:{
        flexDirection:"row",
        alignItems:"center",
        width:"30%",
        justifyContent:"flex-start",
        marginVertical:10,
        marginLeft:15
    },
    colorbox:{
        width:20,
        height:20,
        borderRadius:3,
        backgroundColor:"red",
        marginRight:10
    },
    desc:{
        marginLeft:15,
        fontSize:13,
        marginTop:10
    },
    sheet:{
        position:"absolute",
        left:0,
        right:0,
        bottom:0,
        width: width ,
        borderTopRightRadius:30,
        borderTopLeftRadius:30,
        height:height * 0.35,
        alignItems:"center",
        alignSelf:"center",
        justifyContent:"flex-start",
        backgroundColor:"black",
        zIndex:2
    },
    overlay:{
        width:"100%",
        height:"100%",
        backgroundColor:"rgba(0,0,0,0.6)",
        position:"absolute",
        zIndex:1,
    }
})

export default styles